### ISSUE TITLE
[BUG] Have to set default container in order to switch containers

### ISSUE THREAD

**Issue by Arbifoxx** [hugeBlack/LiveContainer#12]
### Describe the bug

Im not sure if this is as intended or not, but in order to switch the container of an app you must go to the app's settings and set it. Long pressing on the app and selecting the desired container does nothing. Again, unsure if this is the intended functionality or not, but it seems odd to me to list the containers on a long press if it wasn't.

### Instructions to reproduce

1) Open LiveContainer
2) Long press on app with multiple containers
3) Select desired container
4) Container does not change

To successfully switch the container:
1) Open LiveContainer
2) Long press on an app
3) Press Settings
4) select the desired container under Containers
5) select Set as Default Container

### What version of LiveContainer are you using?

3.1.0-release (main/7faf79c)

**Comment by hugeBlack** [comment]
That seems to be an issue with GitHub Actions. The one built on my Mac worked properly. I'm still investigating why.

**Comment by hugeBlack** [comment]
Fixed now, try the latest build
