### ISSUE TITLE
Some apps setting got reset

### ISSUE THREAD

**Issue by seadogVN1** [hugeBlack/LiveContainer#13]
### Describe the bug

Some apps like yt got reverted back to previous state but only some setting

### Instructions to reproduce

Open yt setting
Choose YouTube Plus->SponerBlock->show notifications 
Close the app then reopen
The setting should be reseted
Or
Choose YouTube Plus->Player->Gesture

### What version of LiveContainer are you using?

Version 3.1.0-release (main/fbOc16f)

### Other info

I found only these two setting got reset.The other was fine

**Comment by hugeBlack** [comment]
Should be fixed now. Try latest build

**Comment by seadogVN1** [comment]
The fix work
