### ISSUE TITLE
[BUG] Error with last nightly: zsign improvements

### ISSUE THREAD

**Issue by michael1900** [hugeBlack/LiveContainer#14]
### Describe the bug

It's now impossible to patch SideStore, and the test about the jitless mode failed, i don't know why. Also i see now only the AltStore name. 

Screenshots:

![IMG_0036](https://github.com/user-attachments/assets/bd99a6db-4d8f-472c-b694-73d3a0039952)

![IMG_0037](https://github.com/user-attachments/assets/1752e355-9be0-4300-bf1a-043cb527416d)

**Comment by hugeBlack** [comment]
What’s your SideStore’s version?

**Comment by michael1900** [comment]
> What’s your SideStore’s version?

The same version of tonight, the last nightly and all worked well: https://github.com/SideStore/SideStore/actions/workflows/nightly.yml

Now also re-installing previous LC version the error does not disappear. I would like to know why, since everything was working perfectly

**Comment by hugeBlack** [comment]
Can’t confirm. Might be some random SideStore bug. Try reinstall the latest LC and see.

**Comment by michael1900** [comment]
> Can’t confirm. Might be some random SideStore bug. Try reinstall the latest LC and see.

Already done

**Comment by michael1900** [comment]
Nothing, i installed again SideStore from scratch but LC doesn't seem to recognize it anymore, if patched or not, just like in the screenshots. No matter what i do. Until this morning all worked. It's not a problem about cert or pairing file because i can refresh without errors.

**Comment by michael1900** [comment]
I solved one part. I uninstalled LC app and installed it again and now LC see and patch SideStore, simply reinstalling it didn't help. Now i am installing again all my apps :(

**But there is a problem with kodi, (in use the last LC nighlty) when installing and signing it that i never seen i think:**
![IMG_0040](https://github.com/user-attachments/assets/7eda853c-cf41-4682-8dde-8fb4cc2ea3d5)



**The first time installing kodi LC crashes and if i open LC kodi is installed and "seems" working, if i reinstall it again that error appears.**

**Comment by hugeBlack** [comment]
That's intended. In previous version ZSign doesn't sign all binaries which cause problem in some app. The latest build solved this issue and added this new prompt. In Kodi's case this file is impossible to sign because there's not enough space in its MachO header to place code signature.

**Comment by michael1900** [comment]
> That's intended. In previous version ZSign doesn't sign all binaries which cause problem in some app. The latest build solved this issue and added this new prompt. In Kodi's case this file is impossible to sign because there's not enough space in its MachO header to place code signature.

ok, but for kodi what are the consequences? I mean in this case.

**Comment by hugeBlack** [comment]
As long as Kodi doesn't load this library there won't be any issue. I'm not familiar with Kodi so don't know when the problem will occur.

**Comment by michael1900** [comment]
If for kodi that error is normal I think that this issue can be closed. Honeslty i don't know what's happened before above, maybe in some cases it's necessary uninstall the old LC version before to install a new one and not simply install the new version above the old.
