### ISSUE TITLE
[BUG] Jitless test(?) error with last SideStore 0.6.0

### ISSUE THREAD

**Issue by michael1900** [hugeBlack/LiveContainer#16]
### Describe the bug

Error with last SideStore 0.6.0 :  https://github.com/SideStore/SideStore/actions/workflows/rebase.yml

**Impossible to load package AltStoreCore**

<img width="445" alt="Schermata 2024-12-14 alle 16 06 10" src="https://github.com/user-attachments/assets/8374cfd5-9caa-4135-8500-5f1fb56af7c8" />

**Comment by hugeBlack** [comment]
Wow, are they releasing 0.6.0? Seems like they adopted the new AltStoreCore which requires 1 more library to load. There will be no support for this until they release the nightly version for 0.6.0.

Edit: seems I forgot to use the default signer when testing JIT, I'll fix that.

**Comment by ghost** [comment]
> Wow, are they releasing 0.6.0? Seems like they adopted the new AltStoreCore which requires 1 more library to load. There will be no support for this until they release the nightly version for 0.6.0.
> 
> Edit: seems I forgot to use the default signer when testing JIT, I'll fix that.

0.6.0 is a VERY unstable and experimental version with AltStore 2.0 in it

**Comment by hugeBlack** [comment]
Fixed. Try the latest build.

**Comment by michael1900** [comment]
Fixed 👌

**Comment by michael1900** [comment]
> > Wow, are they releasing 0.6.0? Seems like they adopted the new AltStoreCore which requires 1 more library to load. There will be no support for this until they release the nightly version for 0.6.0.
> > Edit: seems I forgot to use the default signer when testing JIT, I'll fix that.
> 
> 0.6.0 is a VERY unstable and experimental version with AltStore 2.0 in it

Yes, i will switch back in the next hours to the last 0.5.9 nighlty that works perfectly. But not because i find, at least for me, the 0.6 very unstable but because in this last the dev has not yet updated the script/shortcut for the refreshes that i use for automatize ALL.
