### ISSUE TITLE
[BUG] Spotube crash to start

### ISSUE THREAD

**Issue by michael1900** [hugeBlack/LiveContainer#17]
### Describe the bug

https://github.com/KRTirtho/spotube?tab=readme-ov-file

Spotube app crashes instantly to start.
Signed with zsign. Signing with altsign gives an error and this is weird because the dev advices to use Altstore to sideload it.

### Instructions to reproduce

1. Sign with zsign
2. Try to run Spotube
3. Crash

### What version of LiveContainer are you using?

3.1.0 nightly

**Comment by hugeBlack** [comment]
https://github.com/khanhduytran0/LiveContainer/issues/222

Spotube worked fine. Might be some ZSign issues brought by "ZSign improvement". I reverted that change. Update to latest build and force re-sign

**Comment by michael1900** [comment]
> [khanhduytran0#222](https://github.com/khanhduytran0/LiveContainer/issues/222)
> 
> Spotube worked fine. Might be some ZSign issues brought by "ZSign improvement". I reverted that change. Update to latest build and force re-sign

Fixed 👍🏻
