### ISSUE TITLE
[BUG] also feature recommendation: Mass app failure every time I restart my phone.

### ISSUE THREAD

**Issue by ghost** [hugeBlack/LiveContainer#19]
### Describe the bug

I transferred my LC apps from another LC on a different Apple account, kept getting an error about different team IDS, had to force sign ALL my apps. this never happened on older versions of LC 3.0.
now whenever I reboot my phone I get this message “dlopen(/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify, 0x0109): tried: '/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (code signature invalid in <B20509B3-8464-3040-B067-CCD76AACBC24> '/private/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x095C2BF0, codeBlobSize=0x001E9D50), '/private/preboot/Cryptexes/OS/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (no such file), '/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (code signature invalid in <B20509B3-8464-3040-B067-CCD76AACBC24> '/private/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x095C2BF0, codeBlobSize=0x001E9D50), '/private/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (code signature invalid in <B20509B3-8464-3040-B067-CCD76AACBC24> '/private/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x095C2BF0, codeBlobSize=0x001E9D50), '/private/preboot/Cryptexes/OS/private/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (no such file), '/private/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (code signature invalid in <B20509B3-8464-3040-B067-CCD76AACBC24> '/private/var/mobile/Containers/Data/Application/C093E5B9-0697-43C1-9366-7DFC44BA710A/Documents/Applications/com.spotify.client.app/Spotify' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x095C2BF0, codeBlobSize=0x001E9D50)” and I had to force sign all of my 24 apps (which is very time consuming).
if there could be a feature where I could mass force sign all my apps or a fix to this would be great.

### Instructions to reproduce

sideload LC on one SideStore, move the signed apps to another LC on another SideStore with a different Apple ID.

### What version of LiveContainer are you using?

3.1.0

**Comment by hugeBlack** [comment]
Disable "resign only on certificate expires" in lc settings.

If that option is on, lc only checks the expiration date, not the cert, so this will happen.

**Comment by ghost** [comment]
> Disable "resign only on certificate expires" in lc settings.
> 
> 
> 
> If that option is on, lc only checks the expiration date, not the cert, so this will happen.

I keep getting frequent re-signs

**Comment by hugeBlack** [comment]
Maybe we should also keep track of team id to avoid this kind of situation.

**Comment by ghost** [comment]
> Maybe we should also keep track of team id to avoid this kind of situation.

I used to switch apps between LCs of different Apple IDs all the time. there were no problems

**Comment by hugeBlack** [comment]
Please try the new build and see if apps got automatically resigned when moved to a different LC

**Comment by ghost** [comment]
> Please try the new build and see if apps got automatically resigned when moved to a different LC

K

**Comment by ghost** [comment]
> Please try the new build and see if apps got automatically resigned when moved to a different LC

fixed. no longer giving errors when resign only on certificate expires is enabled.
