### ISSUE TITLE
[BUG] cant open any app after installing ios 18.3 beta

### ISSUE THREAD

**Issue by fluxmanch26** [hugeBlack/LiveContainer#20]
### Describe the bug

Hello, i have a problem with livecontainer, installed apps just doesnt work at all, gives me one error all the time after trying to run them
![IMG_0704](https://github.com/user-attachments/assets/d0cd4cfd-5588-493c-ab0b-dcb2a53d2ce6)

### Instructions to reproduce

install sidestore, sideload the livecontainer, install an app in livecontainer, run it

### What version of LiveContainer are you using?

3.1.0

**Comment by hugeBlack** [comment]
Download the latest build from actions, do the patch again and show me the result of jitless diagnose screen

**Comment by fluxmanch26** [comment]
> Download the latest build from actions, do the patch again and show me the result of jitless diagnose screen

![IMG_0705](https://github.com/user-attachments/assets/0e81a251-8cb1-4071-9077-01b3689e5cf6)

**Comment by hugeBlack** [comment]
Weird, can you do a force re-sign? Long press the app -> settings -> force resign

**Comment by fluxmanch26** [comment]
> Weird, can you do a force re-sign? Long press the app -> settings -> force resign

https://github.com/user-attachments/assets/4f27f947-f79c-4740-943b-8aba09039341
still cant open the app

**Comment by hugeBlack** [comment]
Can you try patch SideStore again and see if "Certificate Last Update Date" changes?

**Comment by fluxmanch26** [comment]
> Can you try patch SideStore again and see if "Certificate Last Update Date" changes?

![image](https://github.com/user-attachments/assets/e916b730-f3b0-41ef-8db8-fdd470897031)

**Comment by hugeBlack** [comment]
Hmm, disable "Re-sign Only on certificate expires" and force re-sign again? 

~~I'm downloading iOS 18.3 to see if something went wrong.~~

Edit: Can confirm LiveContainer still works on iOS 18.3beta

**Comment by fluxmanch26** [comment]
> Hmm, disable "Re-sign Only on certificate expires" and force re-sign again? 
> 
> 
> 
> ~~I'm downloading iOS 18.3 to see if something went wrong.~~
> 
> 
> 
> Edit: Can confirm LiveContainer still works on iOS 18.3beta

so, after patching sidestore, apps started to work again, i consider this as a win
