### ISSUE TITLE
Minecraft crashes

### ISSUE THREAD

**Issue by player301** [hugeBlack/LiveContainer#6]
### Describe the issue

I opened Minecraft after installing it via livecontainer, and it just crashes

### Instructions to reproduce

just open Minecraft on livecontainer

### What version of LiveContainer are you using?

3.1.0

**Comment by hugeBlack** [comment]
Fixed, try the latest build

**Comment by player301** [comment]
> Fixed, try the latest build

Bug isn’t fixed in new build

**Comment by hugeBlack** [comment]
Can't confirm. Clean up your keychain in LiveContainer settings and try again

**Comment by player301** [comment]
works now 👍
