### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by seadogVN1** [hugeBlack/LiveContainer#7]
### Describe the bug

Account always sign out except discord for some reason 

### Instructions to reproduce

Try to sign in some apps like youtube, Facebook or instagram then close the app and reopen 

### What version of LiveContainer are you using?

Version 3.1.0-release (main/4cd537e)

### Other info

Reddit couldn’t sign in, twitter couldn’t connect to internet without relog in account.This happened after i cleaned up keychain

**Comment by hugeBlack** [comment]
Fixed for and tested on youtube, Facebook, instagram and twitter, try the latest build. 

~I think reddit just doesn't let you log in if you sideload it. Please use Apollo.~

Edit: Reddit works. I previously failed to login probably because my ip got flagged.
